/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.ui;

import alma.mde.project.ui.internal.ProjectActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ProjectActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ProjectActivator.getInstance().getInjector(ProjectActivator.ORG_XTEXT_EXAMPLE_MYDSL_MYDSL);
	}
	
}
